In [1]:

import urllib
import xml.etree.ElementTree as ET
import urllib
import re
import io, random
import pandas as pd
import time
from datetime import datetime
from sklearn.svm import SVR
import datetime

In [2]:
df = pd.read_csv("abc1.csv")

In [3]:
df.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
2,2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
3,3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
4,4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0

In [4]:
del df["7"]

In [5]:
df.head()

,Unnamed: 0,0,1,2,3,4,5,6,8,9,10,11,12
0,0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
2,2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
3,3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
4,4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0

In [6]:
df.columns = ["Sno","DATE_TIME","PLANT_ID","SOURCE_KEY","AMBIENT_TEMPERATURE","MODULE_TEMPERATURE","IRRADIATION","PLANT_ID","SCE_KEY","DC_POWER","AC_POWER","DAILY_YIELD","TOTAL_YIELD"]

In [7]:
del df["Sno"]

In [8]:
df.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,PLANT_ID,SCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0

In [9]:
df.columns = ["DATE_TIME","PLANT_ID","SCE_KEY","DC_POWER","AC_POWER","DAILY_YIELD","TOTAL_YIELD","PLANT_ID","SOURCE_KEY","AMBIENT_TEMPERATURE","MODULE_TEMPERATURE","IRRADIATION"]

In [10]:
df.head()

,DATE_TIME,PLANT_ID,SCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0

In [11]:
df[100:125]

,DATE_TIME,PLANT_ID,SCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
100,15-05-2020 01:00,4135001,sjndEbLyjtCKgGv,0.0,0.0,0.0,7016832.0,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0
101,15-05-2020 01:00,4135001,uHbuxQJl8lW7ozc,0.0,0.0,0.0,7038681.0,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0
102,15-05-2020 01:00,4135001,wCURE6d3bPkepu2,0.0,0.0,0.0,6782598.0,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0
103,15-05-2020 01:00,4135001,z9Y9gH1T5YWrNuG,0.0,0.0,0.0,7007866.0,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0
104,15-05-2020 01:00,4135001,zBIq5rxdHJRwDNY,0.0,0.0,0.0,6339380.0,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0
105,15-05-2020 01:00,4135001,zVJPv84UY57bAof,0.0,0.0,0.0,7116151.0,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0
106,15-05-2020 01:15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
107,15-05-2020 01:15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
108,15-05-2020 01:15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
109,15-05-2020 01:15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
110,15-05-2020 01:15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
111,15-05-2020 01:15,4135001,VHMLBKoKgIrUVDU,0.0,0.0,0.0,7206408.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
112,15-05-2020 01:15,4135001,WRmjgnKYAwPKWDb,0.0,0.0,0.0,7028673.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
113,15-05-2020 01:15,4135001,ZnxXDlPa8U1GXgE,0.0,0.0,0.0,6522172.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
114,15-05-2020 01:15,4135001,ZoEaEvLYb1n2sOq,0.0,0.0,0.0,7098099.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
115,15-05-2020 01:15,4135001,adLQvlD726eNBSB,0.0,0.0,0.0,6271355.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
116,15-05-2020 01:15,4135001,bvBOhCH3iADSZry,0.0,0.0,0.0,6316803.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
117,15-05-2020 01:15,4135001,iCRJl6heRkivqQ3,0.0,0.0,0.0,7177992.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
118,15-05-2020 01:15,4135001,ih0vzX44oOqAx2f,0.0,0.0,0.0,6185184.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
119,15-05-2020 01:15,4135001,pkci93gMrogZuBj,0.0,0.0,0.0,7169102.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
120,15-05-2020 01:15,4135001,rGa61gmuvPhdLxV,0.0,0.0,0.0,7111493.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
121,15-05-2020 01:15,4135001,sjndEbLyjtCKgGv,0.0,0.0,0.0,7016832.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
122,15-05-2020 01:15,4135001,uHbuxQJl8lW7ozc,0.0,0.0,0.0,7038681.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
123,15-05-2020 01:15,4135001,wCURE6d3bPkepu2,0.0,0.0,0.0,6782598.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0
124,15-05-2020 01:15,4135001,z9Y9gH1T5YWrNuG,0.0,0.0,0.0,7007866.0,4135001,HmiyD2TTLFNqkNe,24.536092,21.968571,0.0

In [12]:
df.to_csv("merged_final.csv")

In [ ]:


#constant parameters
TrainingWindow = 15    #window size is found from historical data
PredictionWindow = 3   #prediction window/prediction horizon
time_sampling = 300	#Should be equal to data refreshing time



#function to read data
def data_traffic_read():
    req = urllib2.Request(url='http://informo.munimadrid.es/informo/tmadrid/pm.xml')

    f = urllib2.urlopen(req)
    xml_str = f.read()
    root = ET.fromstring(xml_str)
    list = []
    for location in root.findall('pm'):
        codigo = location.find('codigo').text
        #here if statement can be added to look for IDs with PM and publish it
        #into different topic
        flag = re.match('PM',codigo)
        if (flag):
            intensity = float(location.find('intensidad').text)
            speed = float(location.find('velocidad').text)
            occupancy = float(location.find('ocupacion').text)
            date = (datetime.datetime.utcnow())
            error = location.find('error').text

            if error == 'N':
                message = {'ID':codigo, 'TrafficIntensity':intensity, 'TrafficSpeed': speed, 'TrafficOccupancy':occupancy, 'Date_UTC': date}
                list.append(message)
    return list

#function to apply prediction based on svr with rbf kernel
def pred(df):
    X = []
    Y = []
    for index, row in df.iterrows():
        X.append([index.hour, index.minute])
        Y.append(row)



    #initializes the model
    svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)


    y_rbf = svr_rbf.fit(X, Y.values.ravel())

    #predicting for next readings

    #first we take the time for the latest reading
    length = len(df)
    df_pred = df[length-1:length]

    for index, row in df_pred.iterrows():
        time_last = index


    print "time_last is {}".format(time_last)
    #extracting time for next 3 predictions

    X_pred = []
    for i in range(3):
        time_new = time_last + datetime.timedelta(seconds = (i+1)*time_sampling)
        X_pred.append([time_new.hour, time_new.minute])

    Y_pred = y_rbf.predict(X_pred)


    return X_pred, Y_pred

#adaptive movie window regression function
def AMWR(df):
    #extracting last readings equivalent to window size

    length = len(df)
    df1 = df[length-TrainingWindow:length]


    df_speed = df1[['Date_UTC','TrafficSpeed']]
    df_speed1 = df_speed.set_index('Date_UTC')
    X_speed, Y_speed = pred(df_speed1)





    df_intensity = df1[['Date_UTC','TrafficIntensity']]
    df_intensity1 = df_intensity.set_index('Date_UTC')
    X_intensity, Y_intensity = pred(df_intensity1)


    for i in range(3):
        print "Expected traffic speed at {}:{} is {}".format(X_speed[i][0], X_speed[i][1], int(Y_speed[i]))
        print "Expected traffic intensity at {}:{} is {}".format(X_intensity[i][0], X_intensity[i][1], int(Y_intensity[i]))


#main function
if __name__ == '__main__':

    total_list = []
    while(1):

        list = data_traffic_read()
        total_list = total_list + list
        df = pd.DataFrame(total_list)
        #print df
        df1 = df[df['ID'] == 'PM10005']
        #print len(df1)

        if len(df1) >= TrainingWindow:
            print "calling prediction algo"
            print "df1 is ", df1
            AMWR(df1)

        else:
            pass

        print "i am sleeping"
        time.sleep(time_sampling)

In [1]:
def AMWR(df):
    #extracting last readings equivalent to window size

    length = len(df)
    df1 = df[length-TrainingWindow:length]


    df_speed = df1[['Date_UTC','TrafficSpeed']]
    df_speed1 = df_speed.set_index('Date_UTC')
    X_speed, Y_speed = pred(df_speed1)





    df_intensity = df1[['Date_UTC','TrafficIntensity']]
    df_intensity1 = df_intensity.set_index('Date_UTC')
    X_intensity, Y_intensity = pred(df_intensity1)


    for i in range(3):
        print "Expected traffic speed at {}:{} is {}".format(X_speed[i][0], X_speed[i][1], int(Y_speed[i]))
        print "Expected traffic intensity at {}:{} is {}".format(X_intensity[i][0], X_intensity[i][1], int(Y_intensity[i]))

SyntaxError: invalid syntax (<ipython-input-1-5696036356bc>, line 22)

In [2]:

#function to apply prediction based on svr with rbf kernel
def pred(df):
    X = []
    Y = []
    for index, row in df.iterrows():
        X.append([index.hour, index.minute])
        Y.append(row)



    #initializes the model
    svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)


    y_rbf = svr_rbf.fit(X, Y.values.ravel())

    #predicting for next readings

    #first we take the time for the latest reading
    length = len(df)
    df_pred = df[length-1:length]

    for index, row in df_pred.iterrows():
        time_last = index


    print "time_last is {}".format(time_last)
    #extracting time for next 3 predictions

    X_pred = []
    for i in range(3):
        time_new = time_last + datetime.timedelta(seconds = (i+1)*time_sampling)
        X_pred.append([time_new.hour, time_new.minute])

    Y_pred = y_rbf.predict(X_pred)


    return X_pred, Y_pred

SyntaxError: invalid syntax (<ipython-input-2-0a011eecde71>, line 26)

In [1]:
def pred(x, y, x_test):
    svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
    y_rbf = svr_rbf.fit(x, y)
    return svr_rbf.predict(x_test)

def AMWR(df):
    x_total = df[["AMBIENT_TEMPERATURE","MODULE_TEMPERATURE","IRRADIATION"]].to_numpy().tolist()
    y_total = df[["DAILY_YIELD"]].to_numpy().tolist()
    x = x_total[:len(df)-1]
    y = y_total[:len(df)-1]
    x_test = x_total[len(df)-1]
    y_test = y_total[len(df)-1]
    y_pred = pred(x,y,x_test)

In [ ]:
if __name__ == "__main__":